[package]
name = "coop"
version = "0.4.1"
edition = "2024"
description = "Isolated VM environment for running Claude Code"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "6.0.0"
indexmap = "2"
libc = "0.2.185"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1.2"
tracing = "0.1"
semver = "1"
sha2 = "0.11"
tempfile = "3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
hex = "0.4.3"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "warn"
panic = "deny"
panic_in_result_fn = "deny"
unimplemented = "deny"
allow_attributes = "deny"
dbg_macro = "deny"
todo = "deny"
print_stdout = "deny"
print_stderr = "deny"
await_holding_lock = "deny"
large_futures = "deny"
exit = "deny"
mem_forget = "deny"
module_name_repetitions = "allow"
similar_names = "allow"
